/**
 * Maps help topic section ids to app route names for Playwright screenshots.
 * null = skip automated route navigation (SVG-only or manual).
 */
export const GUIDE_TO_APP_ROUTE: Record<string, string | null> = {
  'supply-chain-flow': null,

  'admin-users-permissions': 'admin-grid',
  'admin-roles-management': 'admin-grid',
  'admin-system-configuration': 'admin-grid',
  'batch-journey-grid': 'batch-journey',
  'crm-nis-suppliers': 'crm-grid',
  'crm-oil-processors': 'crm-grid',
  'crm-oil-ingredient-suppliers': 'crm-grid',
  'crm-oil-protein-customers': 'crm-grid',
  'crm-kernel-customers': 'crm-grid',
  'dashboard-overview': 'dashboard',
  'data-import-grid': 'data-import-grid',
  'document-management-grid': 'document-management-grid',
  'executive-dashboard': 'executive-dashboard',
  'features-grid': 'features-grid',
  'financial-management-grid': 'financial-management-grid',
  'grower-intake-grid': 'grower-intake-grid',
  'kernel-dispatch-grid': 'kernel-dispatch-grid',
  'kernel-production-grid': 'kernel-production-grid',
  'material-journey-dashboard': 'amanda-dashboard',
  'my-day': 'my-day',
  'oil-dispatch-grid': 'oil-dispatch-grid',
  'oil-production-grid': 'oil-production-grid',
  'palladium-integration-grid': 'palladium-integration-grid',
  'quality-assurance-grid': 'quality-assurance-grid',
  'role-features-grid': 'role-features-grid',
  'role-permissions-grid': 'role-permissions-grid',
  'roles-grid': 'roles-grid',
  'sales-forecasting-grid': 'sales-forecasting-grid',
  'stock-management-grid': 'stock-management-grid',
  'supplier-intake-grid': 'supplier-intake-grid',
  'test-data-sets': 'test-data-grid',
  'test-data-records': 'test-data-grid',
  'test-scenarios-grid': 'test-scenarios-grid',
  'users-grid': 'users-grid',

  'modal-admin-add-role': 'admin-grid',
  'modal-admin-add-user': 'admin-grid',
  'modal-batch-history': 'kernel-production-grid',
  'modal-batch-summary': 'kernel-production-grid',
  'modal-crm-contact': 'crm-grid',
  'modal-end-sample': 'kernel-production-grid',
  'modal-end-sample-view': 'kernel-production-grid',
  'modal-feature': 'features-grid',
  'modal-grower-create-kernel-batch': 'grower-intake-grid',
  'modal-grower-link-sample-to-batch': 'grower-intake-grid',
  'modal-grower-receiving-checklist': 'grower-intake-grid',
  'modal-import-oil-lots': 'stock-management-oil',
  'modal-job-card-view': 'kernel-production-grid',
  'modal-kernel-dispatch': 'kernel-dispatch-grid',
  'modal-kernel-dispatch-form': 'kernel-dispatch-grid',
  'modal-kernel-job-card': 'kernel-production-grid',
  'modal-oil-dispatch': 'oil-dispatch-grid',
  'modal-oil-dispatch-form': 'oil-dispatch-grid',
  'modal-oil-lot': 'stock-management-oil',
  'modal-oil-production-sheet': 'oil-production-grid',
  'modal-production-stages': 'kernel-production-grid',
  'modal-production-stages-view': 'kernel-production-grid',
  'modal-quality-test': 'quality-assurance-grid',
  'modal-raw-material-issued': 'oil-production-grid',
  'modal-receiving-checklist': 'stock-management-kernel',
  'modal-role': 'roles-grid',
  'modal-role-feature': 'role-features-grid',
  'modal-role-permission': 'role-permissions-grid',
  'modal-send-to-dispatch': 'stock-management-kernel',
  'modal-send-to-dispatch-oil': 'stock-management-oil',
  'modal-stock-take': 'stock-management-kernel',
  'modal-supplier-oil-batch': 'supplier-intake-grid',
  'modal-supplier-receiver-checklist': 'supplier-intake-grid',
  'modal-test-data-record': 'test-data-grid',
  'modal-test-data-set': 'test-data-grid',
  'modal-test-scenario': 'test-scenarios-grid',
  'modal-user': 'users-grid',
};
